# Generated by Django 4.0.4 on 2023-05-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0002_bike_plan_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='serie_number',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Número de série'),
        ),
    ]
