# Generated by Django 4.0.4 on 2023-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0003_alter_bike_serie_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='rent',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data de início'),
        ),
    ]
