# Generated by Django 4.0.4 on 2023-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0005_placecategory_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Nome'),
        ),
    ]
