# Generated by Django 4.0.4 on 2023-05-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0006_alter_bike_name_alter_place_name_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='api_image',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Imagem_api'),
        ),
    ]
