# Generated by Django 4.0.4 on 2023-05-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0007_place_api_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Descrição'),
        ),
    ]
