# Generated by Django 4.0.4 on 2023-05-27 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databank', '0009_plancategory_plan_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plancategory',
            options={'verbose_name': 'Categoria de plano', 'verbose_name_plural': 'Categorias de Planos'},
        ),
    ]
